name: my_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.2

environment:
  sdk: '>=3.3.0 <4.0.0'

# Ин блокро пурра нусхабардорӣ кунед

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.1
  flutter_launcher_icons: ^0.13.1
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.6
  image_picker: ^1.0.4 
  intl: ^0.18.1 
  jwt_decoder: ^2.0.1
  http_interceptor: ^2.0.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  polyline_codec: ^0.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          # Вазни дуруст барои Bold
          weight: 700

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo1.png"  
  adaptive_icon_background: "#212121"
  adaptive_icon_foreground: "assets/images/icon_foreground.png"